services:
  mongodb:
    image: mongo:latest
    container_name: productmongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - products

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: productmongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@productmongodb:27017/
    ports:
      - "8084:8084"
    depends_on:
      - mongodb
    networks:
      - products

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      SPRING_DATA_MONGODB_HOST: productmongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: productservice
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - products

volumes:
  mongo-data:

networks:
  products:
    driver: bridge