spring:
    application:
        name: order-service
    datasource:
        url: "jdbc:postgresql://orderpostgres:5432/orders"
        username: "user"
        password: "password"
        driver-class-name: "org.postgresql.Driver"
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: always
logging:
    level:
        org:
            hibernate: DEBUG